services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 2root!()root2
      MYSQL_DATABASE: users_db_test

  app:
    depends_on:
      - mysql
    build: .
    container_name: pp-3-2-bootstrap-app
    restart: on-failure
    ports:
      - "8081:8080"
    links:
      - "mysql:database"
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/users_db_test"
